services:
  - type: web
    name: url-shortener-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: BASE_URL
        value: https://url-shortener-backend.onrender.com